version: "3.5"

# refer: https://postgrest.org/en/stable/install.html#docker
services:

  postgrest:
    image: postgrest/postgrest:latest
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      # The standard connection URI format, documented at
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      PGRST_DB_URI: postgres://admin:nCCGkzg9qs3hPsy7@db:5432/demodb
      # The name of which database schema to expose to REST clients
      PGRST_DB_SCHEMA: public
      # The database role to use when no client authentication is provided
      PGRST_DB_ANON_ROLE: slackbot
      PGRST_OPENAPI_SERVER_PROXY_URI: http://0.0.0.0:3000
    depends_on:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data

  db:
    image: postgres:12
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nCCGkzg9qs3hPsy7

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://0.0.0.0:3000

# Uncomment this if you want to persist the data.
volumes: 
  pgdata: